# Define reusable CSS classes and constants
CLASS_CONTAINER = 'container mx-auto p-4 bg-gray-50 min-h-screen'
CLASS_TABS = 'mb-6'
CLASS_CARD = 'mb-4'
CLASS_FLEX = 'flex flex-wrap gap-4 mt-2 items-start'
CLASS_LABEL = 'text-sm font-medium text-gray-700 mr-2'
CLASS_DROPDOWN = 'w-48'
CLASS_DATEPICKER = 'w-32'
CLASS_BUTTON = 'ml-4 px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700'
CLASS_ERROR = 'text-red-600 mt-2 hidden'